const functions = require("firebase-functions");
const admin = require("firebase-admin");
const path = require("path");
const fs = require("fs");
const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");
const nodemailer = require("nodemailer");
const { ChartJSNodeCanvas } = require("chartjs-node-canvas");

admin.initializeApp();

const FOOTER_TEXT = "Generated by AURAID XR Emergency Training System";

const REPORT_DOC_PATH = "trainees/{traineeId}/sessions/{sessionId}";

async function processReportRequest(snapshot, context) {
  const after = snapshot.data();
  const { sessionId } = context.params;
  const docRef = snapshot.ref;

  if (after.report_sent === true) return null;

  const reportData = after.report_data;
  if (!reportData || typeof reportData !== "object") return null;

  const email = reportData.trainee_email;
  if (!email || typeof email !== "string" || !email.includes("@")) {
    functions.logger.warn("Session report missing valid trainee_email", { sessionId });
    return null;
  }

  functions.logger.info("Processing report request", { sessionId, to: email });

  try {
    const pdfBuffer = await generateReportPdf({ ...reportData, session_id: sessionId });
    await sendReportEmail(email, reportData.trainee_name || "Trainee", pdfBuffer, sessionId);
    await docRef.update({
      report_sent: true,
      report_sent_at: admin.firestore.FieldValue.serverTimestamp(),
    });
    functions.logger.info("Report sent", { sessionId, email });
  } catch (err) {
    const errMsg = err.message || String(err);
    functions.logger.error("Report generation or send failed", { sessionId, error: errMsg, stack: err.stack });
    try {
      await docRef.update({
        report_sent: false,
        report_error: errMsg,
      });
    } catch (updateErr) {
      functions.logger.error("Failed to write report_error", { updateErr: updateErr.message });
    }
    throw err;
  }
  return null;
}

/**
 * When a session document is updated with report_data (and report_sent is not true),
 * generate a PDF and email it, then set report_sent.
 */
exports.onSessionReportRequested = functions
  .region("us-central1")
  .runWith({ timeoutSeconds: 120, memory: "512MB" })
  .firestore.document(REPORT_DOC_PATH)
  .onUpdate((change, context) => processReportRequest(change.after, context));

/**
 * When a session document is created with report_data (e.g. single write from client),
 * process it the same way. Ensures we don't miss if the trigger was onUpdate-only.
 */
exports.onSessionReportRequestedCreate = functions
  .region("us-central1")
  .runWith({ timeoutSeconds: 120, memory: "512MB" })
  .firestore.document(REPORT_DOC_PATH)
  .onCreate((snapshot, context) => processReportRequest(snapshot, context));

/**
 * Line chart of compression force vs sample index / time labels (optional report_data fields).
 * Expects report_data.compression_timestamps and report_data.compression_forces (same length, ≥2 points).
 */
async function generateCompressionChartBuffer(data) {
  const ts = data.compression_timestamps;
  const forces = data.compression_forces;
  if (!Array.isArray(ts) || !Array.isArray(forces) || ts.length === 0 || forces.length === 0) {
    return null;
  }
  const n = Math.min(ts.length, forces.length);
  if (n < 2) return null;

  const labels = ts.slice(0, n).map((t) => {
    if (typeof t === "number" && Number.isFinite(t)) return n > 24 ? String(t.toFixed(2)) : String(t);
    return String(t);
  });
  const values = forces.slice(0, n).map((f) => Number(f));
  if (values.some((v) => Number.isNaN(v))) return null;

  const width = 700;
  const height = 300;
  const canvas = new ChartJSNodeCanvas({ width, height, backgroundColour: "white" });

  const configuration = {
    type: "line",
    data: {
      labels,
      datasets: [
        {
          label: "Compression force",
          data: values,
          borderColor: "rgb(200, 45, 45)",
          borderWidth: 2,
          fill: false,
          tension: 0.15,
          pointRadius: 0,
        },
      ],
    },
    options: {
      animation: false,
      responsive: false,
      plugins: {
        legend: { display: true },
      },
      scales: {
        x: {
          title: { display: true, text: "Time (seconds)" },
          ticks: { maxRotation: 0, autoSkip: true, maxTicksLimit: 14 },
        },
        y: {
          title: { display: true, text: "Force" },
          min: 0,
          max: 1,
        },
      },
    },
  };

  return canvas.renderToBuffer(configuration);
}

/**
 * Build the AURAID CPR Training Report PDF with logo and all sections.
 */
async function generateReportPdf(data) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.TimesRoman);
  const fontBold = await doc.embedFont(StandardFonts.TimesRomanBold);
  const page = doc.addPage([595, 842]);
  const { width, height } = page.getSize();
  const margin = 42;
  const contentWidth = width - margin * 2;
  let y = height - margin;

  const colors = {
    bgTop: rgb(0.96, 0.98, 1),
    bgBottom: rgb(1, 1, 1),
    navy: rgb(0.08, 0.22, 0.45),
    blue: rgb(0.1, 0.45, 0.78),
    text: rgb(0.14, 0.15, 0.17),
    muted: rgb(0.45, 0.49, 0.55),
    border: rgb(0.87, 0.9, 0.95),
    panelBg: rgb(0.98, 0.99, 1),
  };

  // Soft page background bands for a cleaner look.
  page.drawRectangle({ x: 0, y: height * 0.62, width, height: height * 0.38, color: colors.bgTop });
  page.drawRectangle({ x: 0, y: 0, width, height: height * 0.62, color: colors.bgBottom });

  // Header card
  const headerHeight = 126;
  page.drawRectangle({
    x: margin,
    y: y - headerHeight,
    width: contentWidth,
    height: headerHeight,
    color: rgb(1, 1, 1),
    borderColor: colors.border,
    borderWidth: 1,
  });

  // Logo (supports PNG/JPG/JPEG). Skips safely if missing or invalid.
  const logoPath = resolveLogoPath();
  let hasLogo = false;
  let logoBottomY = y - 20;
  let logoCenterX = width / 2;
  try {
    if (logoPath) {
      const logoBytes = fs.readFileSync(logoPath);
      let logoImage = null;
      const lower = logoPath.toLowerCase();
      if (lower.endsWith(".png")) {
        // Some files are mislabeled as .png but contain JPEG bytes. Fallback to JPG.
        try {
          logoImage = await doc.embedPng(logoBytes);
        } catch (_) {
          logoImage = await doc.embedJpg(logoBytes);
        }
      } else if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) {
        // Some files are mislabeled as .jpg but contain PNG bytes. Fallback to PNG.
        try {
          logoImage = await doc.embedJpg(logoBytes);
        } catch (_) {
          logoImage = await doc.embedPng(logoBytes);
        }
      } else {
        // Unknown extension: try PNG first, then JPG.
        try {
          logoImage = await doc.embedPng(logoBytes);
        } catch (_) {
          logoImage = await doc.embedJpg(logoBytes);
        }
      }
      const logoScale = Math.min(152 / logoImage.width, 51 / logoImage.height);
      const logoW = logoImage.width * logoScale;
      const logoH = logoImage.height * logoScale;
      const logoX = (width - logoW) / 2;
      const logoY = y - 19 - logoH;
      page.drawImage(logoImage, {
        x: logoX,
        y: logoY,
        width: logoW,
        height: logoH,
      });
      hasLogo = true;
      logoBottomY = logoY;
      logoCenterX = logoX + logoW / 2;
    }
  } catch (logoErr) {
    functions.logger.warn("Logo skipped (invalid or unreadable image)", {
      path: logoPath || "not found",
      error: logoErr.message,
    });
  }

  // Header title and subtitle
  const titleText = "CPR Training Report";
  const titleWidth = fontBold.widthOfTextAtSize(titleText, 21);
  const titleY = hasLogo ? (logoBottomY - 28) : (y - 52);
  page.drawText(titleText, {
    x: hasLogo ? (logoCenterX - titleWidth / 2) : ((width - titleWidth) / 2),
    y: titleY,
    size: 21,
    font: fontBold,
    color: colors.navy,
  });
  const subtitleText = `Session Date: ${data.session_date || "—"}`;
  const subtitleWidth = font.widthOfTextAtSize(subtitleText, 10);
  page.drawText(subtitleText, {
    x: (width - subtitleWidth) / 2,
    y: titleY - 20,
    size: 10,
    font,
    color: colors.muted,
  });
  y -= headerHeight + 20;

  // Top score chip
  const overall = Number(data.overall_score_percent ?? 0).toFixed(1);
  const performance = String(data.performance_level || "—");
  const scoreChipH = 40;
  const scoreChipW = 236;
  page.drawRectangle({
    x: margin,
    y: y - scoreChipH,
    width: scoreChipW,
    height: scoreChipH,
    color: rgb(1, 1, 1),
    borderColor: colors.border,
    borderWidth: 1,
  });
  const scoreChipTextY = y - 22;
  page.drawText("Overall Score", { x: margin + 12, y: scoreChipTextY, size: 9, font, color: colors.muted });
  page.drawText(`${overall}%  •  ${performance}`, { x: margin + 96, y: scoreChipTextY, size: 10, font: fontBold, color: colors.blue });
  y -= scoreChipH + 12;

  // Section cards
  y = sectionCard(page, font, fontBold, margin, contentWidth, y, "Trainee Information", [
    ["Name", data.trainee_name || "—"],
    ["Email", data.trainee_email || "—"],
    ["Session ID", data.session_id || "—"],
    ["Duration", data.duration_minutes || "—"],
  ], colors);

  y = sectionCard(page, font, fontBold, margin, contentWidth, y, "Performance Metrics", [
    ["Total compressions", String(data.total_compressions ?? 0)],
    ["Compression rate", `${Number(data.compression_rate_bpm ?? 0).toFixed(1)} / min`],
    ["Pressure accuracy", `${Number(data.pressure_accuracy_percent ?? 0).toFixed(1)}%`],
    ["Hand placement accuracy", `${Number(data.hand_placement_accuracy_percent ?? 0).toFixed(1)}%`],
    ["Reaction time", data.reaction_time_display || "N/A"],
  ], colors);

  y = sectionCard(page, font, fontBold, margin, contentWidth, y, "Score Section", [
    ["Overall score", `${Number(data.overall_score_percent ?? 0).toFixed(1)}%`],
    ["Performance level", data.performance_level || "—"],
  ], colors, { compact: true });

  // Footer (Page 1)
  const footerLineY = 14;
  const footerY = 4;
  page.drawLine({
    start: { x: margin, y: footerLineY },
    end: { x: width - margin, y: footerLineY },
    thickness: 0.8,
    color: colors.border,
  });
  page.drawText(FOOTER_TEXT, {
    x: (width - font.widthOfTextAtSize(FOOTER_TEXT, 9)) / 2,
    y: footerY,
    size: 9,
    font: font,
    color: colors.muted,
  });

  // Page 2+: optional compression chart, Quiz Review, then AI Feedback + Result Stamp
  const page2 = doc.addPage([width, height]);
  drawPageBackground(page2, width, height, colors);

  let y2 = height - margin - 12;
  const xContent = margin + 14;

  try {
    const chartBuffer = await generateCompressionChartBuffer(data);
    if (chartBuffer) {
      const chartImage = await doc.embedPng(chartBuffer);
      const titleBaseline = y2 - 18;
      page2.drawText("Compression force over time", {
        x: xContent,
        y: titleBaseline,
        size: 13,
        font: fontBold,
        color: colors.navy,
      });
      const gap = 10;
      const maxChartW = contentWidth - 28;
      const maxChartH = 200;
      const scale = Math.min(maxChartW / chartImage.width, maxChartH / chartImage.height);
      const cW = chartImage.width * scale;
      const cH = chartImage.height * scale;
      const imgBottom = titleBaseline - gap - cH;
      page2.drawImage(chartImage, {
        x: xContent,
        y: imgBottom,
        width: cW,
        height: cH,
      });
      y2 = imgBottom - 20;
    }
  } catch (chartErr) {
    functions.logger.warn("Compression chart skipped", { error: chartErr.message || String(chartErr) });
  }

  const quizCtx = { width, height, margin, contentWidth, colors, font, fontBold };
  const afterQuiz = drawQuizReview(doc, page2, y2, data, quizCtx);
  let lastPage = afterQuiz.page;
  y2 = afterQuiz.y;

  const minYForFeedback = 240;
  if (y2 < minYForFeedback) {
    lastPage = doc.addPage([width, height]);
    drawPageBackground(lastPage, width, height, colors);
    y2 = height - margin - 12;
  }

  y2 = feedbackCard(
    lastPage,
    font,
    fontBold,
    margin,
    contentWidth,
    y2,
    "AI Feedback",
    data.suggestions_for_improvement || "—",
    colors
  );

  await drawResultStamp(doc, lastPage, {
    overallScore: Number(data.overall_score_percent ?? 0),
    performanceLevel: String(data.performance_level || ""),
    x: width - margin - 230,
    y: 18,
    maxWidth: 210,
    maxHeight: 140,
  });

  lastPage.drawLine({
    start: { x: margin, y: footerLineY },
    end: { x: width - margin, y: footerLineY },
    thickness: 0.8,
    color: colors.border,
  });
  lastPage.drawText(FOOTER_TEXT, {
    x: (width - font.widthOfTextAtSize(FOOTER_TEXT, 9)) / 2,
    y: footerY,
    size: 9,
    font: font,
    color: colors.muted,
  });

  return Buffer.from(await doc.save());
}

function sectionCard(page, font, fontBold, margin, contentWidth, y, title, rows, colors, options = {}) {
  const compact = options.compact === true;
  const titleGap = compact ? 34 : 38;
  const lineHeight = 16;
  const rowGap = compact ? 6 : 10;
  const textStartX = margin + 16;
  const labelWidth = 176;
  const valueColumnGap = 8;
  const cardPaddingY = compact ? 14 : 18;
  const availableValueWidth = contentWidth - 28 - labelWidth - valueColumnGap;

  let dynamicHeight = cardPaddingY + (compact ? 16 : 20);
  for (const [label, value] of rows) {
    const lines = wrapLines(font, 11, String(value), availableValueWidth);
    dynamicHeight += Math.max(lineHeight, lines.length * lineHeight) + rowGap;
  }
  dynamicHeight += cardPaddingY + (compact ? 0 : 4);

  page.drawRectangle({
    x: margin,
    y: y - dynamicHeight,
    width: contentWidth,
    height: dynamicHeight,
    color: colors.panelBg,
    borderColor: colors.border,
    borderWidth: 1,
  });

  page.drawText(title, {
    x: textStartX,
    y: y - (compact ? 20 : 24),
    size: 13,
    font: fontBold,
    color: colors.navy,
  });
  let rowY = y - titleGap;

  for (let idx = 0; idx < rows.length; idx++) {
    const [label, value] = rows[idx];
    const valueLines = wrapLines(font, 11, String(value), availableValueWidth);
    const maxLines = 3;
    const linesToDraw = valueLines.slice(0, maxLines);
    const rowHeight = Math.max(lineHeight, linesToDraw.length * lineHeight);

    const textBaselineY = rowY - 1;

    page.drawText(`${label}`, {
      x: textStartX,
      y: textBaselineY,
      size: 10,
      font: fontBold,
      color: colors.muted,
    });

    let valY = textBaselineY;
    const valueX = textStartX + labelWidth + valueColumnGap;

    // Values may wrap to multiple lines
    for (const line of linesToDraw) {
      page.drawText(line, {
        x: valueX,
        y: valY,
        size: 11,
        font,
        color: colors.text,
      });
      valY -= lineHeight;
    }

    // Row separator aligned closer to text baseline so text visually sits on the line.
    if (idx < rows.length - 1) {
      const separatorY = textBaselineY - 4;
      page.drawLine({
        start: { x: textStartX, y: separatorY },
        end: { x: margin + contentWidth - 16, y: separatorY },
        thickness: 0.6,
        color: colors.border,
      });
    }

    rowY -= rowHeight + rowGap;
  }

  return y - dynamicHeight - (compact ? 10 : 14);
}

function feedbackCard(page, font, fontBold, margin, contentWidth, y, title, feedbackText, colors) {
  const textStartX = margin + 16;
  const titleY = y - 24;
  const contentStartY = y - 52;
  const feedbackLines = wrapLines(font, 11, String(feedbackText), contentWidth - 32).slice(0, 3);
  const lineHeight = 16;

  const cardHeight = 82 + feedbackLines.length * lineHeight;
  page.drawRectangle({
    x: margin,
    y: y - cardHeight,
    width: contentWidth,
    height: cardHeight,
    color: colors.panelBg,
    borderColor: colors.border,
    borderWidth: 1,
  });

  page.drawText(title, {
    x: textStartX,
    y: titleY,
    size: 13,
    font: fontBold,
    color: colors.navy,
  });

  page.drawText("Suggestions for improvement", {
    x: textStartX,
    y: contentStartY,
    size: 10,
    font: fontBold,
    color: colors.muted,
  });

  let lineY = contentStartY - 18;
  for (const line of feedbackLines) {
    page.drawText(line, {
      x: textStartX,
      y: lineY,
      size: 11,
      font,
      color: colors.text,
    });
    lineY -= lineHeight;
  }

  return y - cardHeight - 28;
}

function wrapLines(font, size, text, maxWidth) {
  if (!text || text.length === 0) return [""];
  const lines = [];
  const words = text.split(/\s+/);
  let current = "";
  for (let i = 0; i < words.length; i++) {
    const next = current ? `${current} ${words[i]}` : words[i];
    const w = font.widthOfTextAtSize(next, size);
    if (w > maxWidth && current.length > 0) {
      lines.push(current);
      current = words[i];
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function drawPageBackground(page, width, height, colors) {
  page.drawRectangle({ x: 0, y: height * 0.62, width, height: height * 0.38, color: colors.bgTop });
  page.drawRectangle({ x: 0, y: 0, width, height: height * 0.62, color: colors.bgBottom });
}

function normalizeQuizItems(raw) {
  if (!Array.isArray(raw)) return [];
  return raw.map((it) => {
    const q = it == null ? {} : it;
    return {
      question: String(q.question ?? "").replace(/\s+/g, " ").trim(),
      user_answer: String(q.user_answer ?? "—"),
      ok: q.is_correct === true || q.is_correct === "true" || q.is_correct === 1,
      correct: q.correct_answer != null && String(q.correct_answer).length > 0 ? String(q.correct_answer) : "",
    };
  });
}

function drawQuizReview(doc, startPage, yStart, data, ctx) {
  const { width, height, margin, contentWidth, colors, font, fontBold } = ctx;
  const items = normalizeQuizItems(data.quiz_items);
  if (items.length === 0) return { page: startPage, y: yStart };

  let page = startPage;
  let y = yStart;
  const x = margin + 14;
  const maxW = contentWidth - 28;
  const bodySize = 10;
  const lineStep = 12;
  const betweenBlockGap = 2;
  /** Extra points between “Quiz Review” baseline and first question baseline (in addition to quizTitleBodyBaselineGap). */
  const headingToQuestionsGap = 5;
  const green = rgb(0.1, 0.45, 0.2);
  const red = rgb(0.55, 0.15, 0.15);

  const quizTitleSize = 13;
  const quizTitleTopInset = 18;
  const quizTitleBodyBaselineGap = 14;
  const quizHeaderVerticalReserve =
    quizTitleTopInset + quizTitleBodyBaselineGap + headingToQuestionsGap;

  let continued = false;
  /** After a page break, draw “Quiz Review (continued)” before the next item. */
  let needQuizHeader = false;

  const drawSectionHeader = () => {
    const title = continued ? "Quiz Review (continued)" : "Quiz Review";
    const titleBaseline = y - quizTitleTopInset;
    page.drawText(title, {
      x,
      y: titleBaseline,
      size: quizTitleSize,
      font: fontBold,
      color: colors.navy,
    });
    y = titleBaseline - quizTitleBodyBaselineGap - headingToQuestionsGap;
  };

  drawSectionHeader();

  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    const qLines = wrapLines(font, bodySize, `${i + 1}. ${it.question}`, maxW).slice(0, 4);
    const uLines = wrapLines(font, bodySize, `Your answer: ${it.user_answer}`, maxW).slice(0, 3);
    const cLines =
      !it.ok && it.correct
        ? wrapLines(font, bodySize, `Correct answer: ${it.correct}`, maxW).slice(0, 3)
        : [];
    let extraBetweenGap = 0;
    if (qLines.length > 0 && uLines.length > 0) extraBetweenGap += betweenBlockGap;
    if (uLines.length > 0 && cLines.length > 0) extraBetweenGap += betweenBlockGap;
    const blockH = 6 + (qLines.length + uLines.length + cLines.length) * lineStep + extraBetweenGap;
    const minY = continued ? 72 : 260;

    const headerReserve = needQuizHeader ? quizHeaderVerticalReserve : 0;
    if (y - headerReserve - blockH < minY) {
      page = doc.addPage([width, height]);
      drawPageBackground(page, width, height, colors);
      y = height - margin - 12;
      continued = i > 0;
      needQuizHeader = true;
    }

    if (needQuizHeader) {
      drawSectionHeader();
      needQuizHeader = false;
    }

    let ty = y;
    for (const ln of qLines) {
      page.drawText(ln, { x, y: ty, size: bodySize, font, color: colors.text });
      ty -= lineStep;
    }
    if (qLines.length > 0 && uLines.length > 0) ty -= betweenBlockGap;
    for (const ln of uLines) {
      page.drawText(ln, { x, y: ty, size: bodySize, font, color: it.ok ? green : red });
      ty -= lineStep;
    }
    if (uLines.length > 0 && cLines.length > 0) ty -= betweenBlockGap;
    for (const ln of cLines) {
      page.drawText(ln, { x, y: ty, size: bodySize, font: fontBold, color: colors.navy });
      ty -= lineStep;
    }
    y = ty - 8;
  }

  return { page, y };
}

function resolveLogoPath() {
  const candidates = [
    path.join(__dirname, "assets", "auraid-logo.png"),
    path.join(__dirname, "assets", "auraid-logo.jpg"),
    path.join(__dirname, "assets", "auraid-logo.jpeg"),
    path.join(__dirname, "assets", "AURAID-logo.png"),
    path.join(__dirname, "assets", "AURAID-logo.jpg"),
    path.join(__dirname, "assets", "AURAID-logo.jpeg"),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  // Last resort: first file in /assets containing "auraid" with supported extension.
  const assetsDir = path.join(__dirname, "assets");
  if (fs.existsSync(assetsDir)) {
    const files = fs.readdirSync(assetsDir);
    const match = files.find((f) => /auraid/i.test(f) && /\.(png|jpe?g)$/i.test(f));
    if (match) return path.join(assetsDir, match);
    // fallback: first supported image file in assets
    const anyImage = files.find((f) => /\.(png|jpe?g)$/i.test(f));
    if (anyImage) return path.join(assetsDir, anyImage);
  }
  return null;
}

function resolveStampPath(type) {
  const assetsDir = path.join(__dirname, "assets");
  const candidates = type === "pass"
    ? [
        "stamp-pass.png",
        "stamp_pass.png",
        "pass-stamp.png",
        "pass.png",
        "passed.png",
      ]
    : [
        "stamp-fail.png",
        "stamp_fail.png",
        "fail-stamp.png",
        "fail.png",
        "failed.png",
      ];

  for (const name of candidates) {
    const p = path.join(assetsDir, name);
    if (fs.existsSync(p)) return p;
  }

  // Flexible fallback: any image containing pass/failed words.
  if (fs.existsSync(assetsDir)) {
    const files = fs.readdirSync(assetsDir);
    const rx = type === "pass" ? /(pass|passed)/i : /(fail|failed)/i;
    const match = files.find((f) => rx.test(f) && /\.(png|jpe?g)$/i.test(f));
    if (match) return path.join(assetsDir, match);
  }
  return null;
}

function isPassed(overallScore, performanceLevel) {
  // Primary rule: score >= 70 is pass.
  if (!Number.isNaN(overallScore) && overallScore >= 70) return true;
  // Secondary rule from label if score is unavailable.
  const lvl = (performanceLevel || "").toLowerCase();
  return lvl.includes("excellent") || lvl.includes("good") || lvl.includes("pass");
}

async function drawResultStamp(doc, page, opts) {
  const passed = isPassed(opts.overallScore, opts.performanceLevel);
  const stampPath = resolveStampPath(passed ? "pass" : "fail");
  if (!stampPath) return;

  try {
    const bytes = fs.readFileSync(stampPath);
    let img;
    const lower = stampPath.toLowerCase();
    if (lower.endsWith(".png")) {
      try { img = await doc.embedPng(bytes); } catch (_) { img = await doc.embedJpg(bytes); }
    } else {
      try { img = await doc.embedJpg(bytes); } catch (_) { img = await doc.embedPng(bytes); }
    }
    const scale = Math.min(opts.maxWidth / img.width, opts.maxHeight / img.height);
    const w = img.width * scale;
    const h = img.height * scale;
    page.drawImage(img, {
      x: opts.x + (opts.maxWidth - w),
      y: opts.y,
      width: w,
      height: h,
      opacity: 0.95,
    });
  } catch (err) {
    functions.logger.warn("Stamp skipped (invalid image)", { path: stampPath, error: err.message });
  }
}

/**
 * Send the report PDF to the trainee's email.
 * Configure SMTP via Firebase config or environment:
 *   firebase functions:config:set smtp.user="..." smtp.pass="..." smtp.host="smtp.gmail.com" smtp.port="587"
 * Or use SendGrid: set sendgrid.api_key and use SendGrid transport.
 */
async function sendReportEmail(toEmail, traineeName, pdfBuffer, sessionId) {
  const config = functions.config();
  const smtpUser = config.smtp?.user || process.env.SMTP_USER;
  const smtpPass = config.smtp?.pass || process.env.SMTP_PASS;
  const smtpHost = config.smtp?.host || process.env.SMTP_HOST || "smtp.gmail.com";
  const smtpPort = parseInt(config.smtp?.port || process.env.SMTP_PORT || "587", 10);
  const fromAddress = config.smtp?.from || process.env.SMTP_FROM || smtpUser;

  if (!smtpUser || !smtpPass) {
    functions.logger.error("SMTP not configured: smtp.user or smtp.pass missing in functions config");
    throw new Error(
      "Email not configured. Set Firebase config: firebase functions:config:set smtp.user=... smtp.pass=..."
    );
  }

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: { user: smtpUser, pass: smtpPass },
  });

  await transporter.sendMail({
    from: fromAddress,
    to: toEmail,
    subject: `AURAID CPR Training Report – ${sessionId}`,
    text: `Hello ${traineeName},\n\nPlease find your AURAID CPR Training Report attached.\n\n${FOOTER_TEXT}`,
    attachments: [
      {
        filename: `AURAID-CPR-Report-${sessionId}.pdf`,
        content: pdfBuffer,
      },
    ],
  });
}

// Local utility export for PDF preview script (no email).
module.exports.generateReportPdfPreview = generateReportPdf;
